# https://bohumirzamecnik.cz/blog/2018/gitlab-docker-compose-tests/

stages:
  - build
  - test

services:
  - name: docker:dind
  - entrypoint: ["env", "-u", "DOCKER_HOST"]
  - command: ["dockerd-entrypoint.sh"]
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE: sdp-dal-receive:${CI_COMMIT_SHA}

build-image:
  stage: build
  image: docker:stable
  script:
    - docker build -f sdp-dal-receive/Dockerfile -t ${IMAGE} --pull .

integration-test:
  stage: test
  image: docker:latest
  before_script:
    - apk add --no-cache py-pip bash git
    - pip install docker-compose
  script:
    - tests/integration/integration_tests.sh