# https://bohumirzamecnik.cz/blog/2018/gitlab-docker-compose-tests/

stages:
  - build
  - test

variables:
  IMAGE: sdp-dal-receive:${CI_COMMIT_SHA}

build-image:
  stage: build
  image: docker:latest
  script:
    - docker build -f sdp-dal-receive/Dockerfile -t ${IMAGE} --pull .

integration-test:
  stage: test
  image: docker:latest
  before_script:
    - apk add --no-cache py-pip bash git
    - pip install docker-compose
  script:
    - tests/integration/integration_tests.sh